env:
  browser: true
  node: true
  es6: true
  jest: true

rules:
  no-console: 0
  no-inner-declarations: 0
  no-unused-vars: warn
  prefer-const: warn

extends:
  - eslint:recommended
  - plugin:jest/recommended
